// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Pacevite.Api.Infrastructure.Persistence;
using Pacevite.Api.Infrastructure.Persistence.Compiled;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AppDbContext), typeof(AppDbContextModel))]
