// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Pacevite.Api.Infrastructure.Persistence.Compiled
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("8b0a495f-cf6a-4d5c-86e9-0489bae14d1b"), entityTypeCount: 11)
        {
        }

        partial void Initialize()
        {
            var identityRole = IdentityRoleEntityType.Create(this);
            var identityRoleClaim = IdentityRoleClaimEntityType.Create(this);
            var identityUser = IdentityUserEntityType.Create(this);
            var identityUserClaim = IdentityUserClaimEntityType.Create(this);
            var identityUserLogin = IdentityUserLoginEntityType.Create(this);
            var identityUserRole = IdentityUserRoleEntityType.Create(this);
            var identityUserToken = IdentityUserTokenEntityType.Create(this);
            var @event = EventEntityType.Create(this);
            var eventSplit = EventSplitEntityType.Create(this);
            var refreshToken = RefreshTokenEntityType.Create(this);
            var syncConnection = SyncConnectionEntityType.Create(this);

            IdentityRoleClaimEntityType.CreateForeignKey1(identityRoleClaim, identityRole);
            IdentityUserClaimEntityType.CreateForeignKey1(identityUserClaim, identityUser);
            IdentityUserLoginEntityType.CreateForeignKey1(identityUserLogin, identityUser);
            IdentityUserRoleEntityType.CreateForeignKey1(identityUserRole, identityRole);
            IdentityUserRoleEntityType.CreateForeignKey2(identityUserRole, identityUser);
            IdentityUserTokenEntityType.CreateForeignKey1(identityUserToken, identityUser);
            EventEntityType.CreateForeignKey1(@event, syncConnection);
            EventSplitEntityType.CreateForeignKey1(eventSplit, @event);

            IdentityRoleEntityType.CreateAnnotations(identityRole);
            IdentityRoleClaimEntityType.CreateAnnotations(identityRoleClaim);
            IdentityUserEntityType.CreateAnnotations(identityUser);
            IdentityUserClaimEntityType.CreateAnnotations(identityUserClaim);
            IdentityUserLoginEntityType.CreateAnnotations(identityUserLogin);
            IdentityUserRoleEntityType.CreateAnnotations(identityUserRole);
            IdentityUserTokenEntityType.CreateAnnotations(identityUserToken);
            EventEntityType.CreateAnnotations(@event);
            EventSplitEntityType.CreateAnnotations(eventSplit);
            RefreshTokenEntityType.CreateAnnotations(refreshToken);
            SyncConnectionEntityType.CreateAnnotations(syncConnection);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.9");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
